---
- name: Déployer l'application Flask
  hosts: 192.168.88.132
  become: true
    tasks:
    - name: Install dependencies
      apt:
        name:
          - python3-pip
          - ufw
        state: present
      become: true

    - name: Install Python packages
      pip:
        requirements: /requirements.txt   # Replace with actual path

    - name: Allow SSH traffic
      ufw:
        rule: allow
        port: '22'
        proto: tcp

    - name: Allow HTTP traffic
      ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: Enable UFW
      ufw:
        state: enabled
        enabled: yes

    - name: Start Flask app with Gunicorn
      shell: |
        cd /path/to/app   # Replace with actual path
        gunicorn --bind 0.0.0.0:80 app:app
