- name: Deploy Flask Application
  hosts: web
  become: true
    
  tasks:
    - name: Install system dependencies
      apt:
        name:
          - python3-venv
          - python3-pip
          - ufw
        state: present
      become: true

    - name: Create Python virtual environment
      shell: |
        if [ ! -d "/home/kali/venv" ]; then
          python3 -m venv /home/kali/venv
        fi

    - name: Clone Flask application repository
      git:
        repo: 'https://github.com/abdorhl/appFlask.git'
        dest: '/home/kali/appFlask'
        version: 'main'

    - name: Install Python packages from requirements.txt
      command: "/home/kali/venv/bin/pip install -r /home/kali/appFlask/requirements.txt"
      become_user: kali

    - name: Allow SSH traffic
      ufw:
        rule: allow
        port: '22'
        proto: tcp

    - name: Enable UFW
      ufw:
        state: enabled

    - name: Allow HTTP traffic
      ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: Start Flask app with Gunicorn
      shell: |
        cd /home/kali/appFlask && /home/kali/venv/bin/gunicorn --bind 0.0.0.0:80 app:app
      become_user: kali
