- name: Deploy Flask Application
  hosts: web
  become: true
    
  tasks:
    - name: Install system dependencies
      apt:
        name:
          - python3-venv
          - python3-pip
          - ufw
        state: present
      become: true

    - name: Create Python virtual environment
      shell: |
        if [ ! -d "/home/kali/venv" ]; then
          python3 -m venv /home/kali/venv
        fi
      # This ensures that the virtualenv is created only if it doesn't already exist.
      
    - name: Install Python packages from requirements.txt
      command: "/home/kali/venv/bin/pip install -r /path/to/your/requirements.txt"
      become_user: kali  # Ensure this is executed as the kali user

    - name: Allow SSH traffic
      ufw:
        rule: allow
        port: '22'
        proto: tcp

    - name: Allow HTTP traffic
      ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: Enable UFW
      ufw:
        state: enabled
        enabled: yes

    - name: Start Flask app with Gunicorn
      shell: |
        cd /path/to/your/app  # Replace with actual path to your Flask app
        /home/kali/venv/bin/gunicorn --bind 0.0.0.0:80 app:app
